"""Added fairness score  migration

Revision ID: 6b755c02fc17
Revises: 4196737e4266
Create Date: 2023-07-26 15:59:06.636055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b755c02fc17'
down_revision = '4196737e4266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fairness_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_results', schema=None) as batch_op:
        batch_op.drop_column('fairness_score')

    # ### end Alembic commands ###
